'use strict';
// Authenticated desktop rendering handoff. This service authorizes only approved
// own-process O artifacts; it never accesses another process or injects code.
const crypto=require('node:crypto'),fs=require('node:fs'),store=require('./desktopBootstrapStore');
const HANDOFF_MS=120000,SESSION_MS=120000,TRANSFER_RECOVERY_MS=30000,CHUNK_SIZE=262144;
const TERMINAL=['CLOSED','REVOKED','EXPIRED'];
const sha512=value=>crypto.createHash('sha512').update(value).digest('hex');
const sha=value=>crypto.createHash('sha256').update(value).digest('hex');
const plain=value=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.getPrototypeOf(value)===Object.prototype;
const id=()=>crypto.randomBytes(12).toString('hex').toUpperCase();
const nonce=()=>crypto.randomBytes(24).toString('hex');
const now=()=>Date.now();
function Boot(){return require('./desktopBootstrap');}
function Fail(code,status=403){Boot().Fail(code,status);}
function Fields(body,names){if(!plain(body)||Object.keys(body).some(k=>!['action',...names].includes(k)))Fail('BOOTSTRAP_INPUT_INVALID',400);}
function Rows(){return store.Load().overlays||{};}
function Ticket(row){return Token('OVERLAY-HANDOFF',row.id,row.ticketNonce);}
function SessionToken(row){return Token('OVERLAY-SESSION',row.sessionId,row.sessionNonce);}
function Token(domain,key,value){if(!value)Fail('BOOTSTRAP_SESSION_CLOSED');return crypto.createHmac('sha256',Buffer.from(store.Load().secret,'hex')).update(['GAME-OVERLAY-V1',domain,key,value].join('|')).digest('base64url');}
function Canonical(row,kind){const artifact=store.Load().artifacts[row.releaseId];return ['GAME-OVERLAY-'+kind+'-V2','3',row.id,row.parentSessionId,row.deviceId,row.machineId,artifact.id,artifact.sha512,artifact.crc64,artifact.xxh3_128,artifact.blake3,artifact.codeSha512,artifact.codeCrc64,artifact.codeXxh3_128,artifact.codeBlake3,String(artifact.size),row.ticketBinding,String(row.expiresAt)].join('\n');}
function License(row){const license=require('./desktopLicenses').DB().licenses[row.licenseId];if(!license||!license.consumed||license.status!=='USED'||license.releasedAt||license.expiresAt&&license.expiresAt<=now()||license.deviceId!==row.deviceId||license.bootstrapSessionId!==row.parentSessionId)Fail('DESKTOP_ACTIVATION_INVALID');require('./desktopMachinePolicy').AssertAllowed(row.machineId,row.machinePolicyGeneration,row.parentSessionId);return license;}
function Transferred(row,parent){return row.transferVersion===1&&Number.isSafeInteger(row.transferredAt)&&parent?.closedByOverlay===true&&parent.overlayTransferVersion===1&&parent.transferredOverlayId===row.id&&parent.transferredAt===row.transferredAt&&parent.status==='CLOSED';}
function RequireArtifact(row){const db=store.Load(),parent=db.flows[row.parentFlowId];if(!parent||parent.overlayReleaseId!==row.releaseId||(!Transferred(row,parent)&&(parent.status!=='CLAIMED'||parent.sessionExpiresAt<=now()))||parent.sessionId!==row.parentSessionId||parent.licenseId!==row.licenseId)Fail('BOOTSTRAP_FLOW_INVALID');require('./desktopSecurityAuthority').RequireArtifact(db.artifacts[row.releaseId]);require('./desktopSecurityOperations').RequireRuntimePair(db.artifacts[db.launchers[parent.launcherId]?.artifactId],db.artifacts[parent.releaseId],db.artifacts[row.releaseId]);return db.artifacts[row.releaseId];}
function Live(row){if(!row)Fail('BOOTSTRAP_SESSION_INVALID',401);if(TERMINAL.includes(row.status))Fail(row.status==='EXPIRED'?'BOOTSTRAP_EXPIRED':row.status==='REVOKED'?'BOOTSTRAP_REVOKED':'BOOTSTRAP_SESSION_CLOSED');if((row.status==='CLAIMED'?row.sessionExpiresAt:row.expiresAt)<=now())Fail('BOOTSTRAP_EXPIRED');License(row);return RequireArtifact(row);}
function Retire(row){row.retiredAt||=now();delete row.ticketNonce;delete row.sessionNonce;delete row.claimRecoveryUntil;delete row.claimFingerprint;row.chunkOffsets=[];require('./desktopSecurityAuthority').RetireContext(row,'O');require('./desktopIntegrityReports').RetireContext(row);}
function Prepare(parent,license,requestId,fingerprint){
 Prune();const db=store.Load(),artifact=db.artifacts[parent.overlayReleaseId];if(!artifact||artifact.component!=='O')Fail('BOOTSTRAP_OVERLAY_NOT_READY',409);
 if(parent.status!=='CLAIMED'||parent.licenseId!==license.id)Fail('BOOTSTRAP_LICENSE_MISMATCH');
 const prior=Object.values(Rows()).find(r=>r.parentFlowId===parent.id);
 if(prior){if(prior.requestId!==requestId||prior.fingerprint!==fingerprint)Fail('BOOTSTRAP_REQUEST_REUSED',409);Live(prior);if(prior.status!=='PREPARED')Fail('BOOTSTRAP_LAUNCHER_USED',409);return PrepareResult(prior);}
 const row={id:id(),sessionId:id(),parentFlowId:parent.id,parentSessionId:parent.sessionId,launcherId:parent.launcherId,releaseId:artifact.id,licenseId:license.id,deviceId:parent.deviceId,publicKey:parent.publicKey,machineId:parent.machineId,machinePolicyGeneration:parent.machinePolicyGeneration,requestId,fingerprint,status:'PREPARED',createdAt:now(),expiresAt:Math.min(now()+HANDOFF_MS,parent.sessionExpiresAt,license.expiresAt||Number.MAX_SAFE_INTEGER),ticketNonce:nonce(),chunkOffsets:[],lastVerifiedAt:0};
 row.ticketHash=sha(Ticket(row));row.ticketBinding=sha512(Ticket(row));License(row);RequireArtifact(row);Boot().ReadArtifactBytes(artifact);
 store.Atomic(next=>{next.overlays||={};if(Object.values(next.overlays).some(r=>r.parentFlowId===parent.id))Fail('BOOTSTRAP_REQUEST_REUSED',409);next.overlays[row.id]=row;});
 Audit('PREPARED',row);return PrepareResult(row);
}
function PrepareResult(row){return {overlayId:row.id,parentSessionId:row.parentSessionId,overlayTicket:Ticket(row),release:Boot().Release(store.Load().artifacts[row.releaseId]),chunkSize:CHUNK_SIZE,expiresAt:row.expiresAt,finishCanonical:Canonical(row,'FINISH'),claimCanonical:Canonical(row,'CLAIM')};}
function TicketRow(body){const row=Rows()[body.overlayId];if(!row||!Boot().EqualHash(body.overlayTicket,row.ticketHash))Fail('BOOTSTRAP_FLOW_INVALID',401);Live(row);return row;}
function Chunk(body){Fields(body,['overlayId','overlayTicket','offset']);const row=TicketRow(body);if(row.status!=='PREPARED')Fail('BOOTSTRAP_LAUNCHER_USED',409);const parent=store.Load().flows[row.parentFlowId];if(parent.status!=='CLAIMED'||parent.sessionExpiresAt<=now())Fail('BOOTSTRAP_SESSION_CLOSED');const artifact=RequireArtifact(row);
 if(!Number.isSafeInteger(body.offset)||body.offset<0||body.offset>=artifact.size||body.offset%CHUNK_SIZE)Fail('BOOTSTRAP_INPUT_INVALID',400);
 const size=Math.min(CHUNK_SIZE,artifact.size-body.offset),bytes=Buffer.alloc(size);let fd;
 try{fd=fs.openSync(store.ArtifactPath(artifact.id),fs.constants.O_RDONLY|(fs.constants.O_NOFOLLOW||0));const st=fs.fstatSync(fd);if(!st.isFile()||st.size!==artifact.size)throw Error();let at=0;while(at<size){const n=fs.readSync(fd,bytes,at,size-at,body.offset+at);if(!n)throw Error();at+=n;}}
 catch(_){Fail('BOOTSTRAP_ARTIFACT_INVALID',503);}finally{if(fd!==undefined)fs.closeSync(fd);}
 if(!row.chunkOffsets.includes(body.offset))store.Atomic(next=>next.overlays[row.id].chunkOffsets.push(body.offset));return {offset:body.offset,data:bytes.toString('base64'),size};
}
function Finish(body){Fields(body,['overlayId','overlayTicket','signature']);const row=TicketRow(body);if(!['PREPARED','READY'].includes(row.status))Fail('BOOTSTRAP_LAUNCHER_USED',409);Boot().Verify(row,Canonical(row,'FINISH'),body.signature);const artifact=RequireArtifact(row);
 if(row.status==='PREPARED'){
  const parent=store.Load().flows[row.parentFlowId];if(parent.status!=='CLAIMED'||parent.sessionExpiresAt<=now())Fail('BOOTSTRAP_SESSION_CLOSED');
  if(row.chunkOffsets.length!==Math.ceil(artifact.size/CHUNK_SIZE))Fail('BOOTSTRAP_DOWNLOAD_INCOMPLETE',409);Boot().ReadArtifactBytes(artifact);
  store.Atomic(next=>{const item=next.overlays[row.id],flow=next.flows[row.parentFlowId];if(item.status!=='PREPARED'||flow.status!=='CLAIMED')Fail('BOOTSTRAP_SESSION_CLOSED');item.status='READY';item.readyAt=now();});
  Audit('READY',row);
 }
 return {overlayId:row.id,overlayTicket:body.overlayTicket,claimCanonical:Canonical(row,'CLAIM'),expiresAt:row.expiresAt};
}
function Claim(body){Fields(body,['overlayId','overlayTicket','signature','binarySha512','crc64','oCodeSha512','oCodeCrc64']);const row=TicketRow(body),fingerprint=sha(JSON.stringify([body.overlayId,body.overlayTicket,body.signature,body.binarySha512,body.crc64,body.oCodeSha512,body.oCodeCrc64]));if(row.status==='CLAIMED'){if(row.claimRecoveryUntil<=now()||!row.claimRecoveryUntil||row.claimFingerprint!==fingerprint)Fail('BOOTSTRAP_LAUNCHER_USED',409);Boot().Verify(row,Canonical(row,'CLAIM'),body.signature);return ClaimResult(row);}if(row.status!=='READY')Fail('BOOTSTRAP_LAUNCHER_USED',409);const artifact=RequireArtifact(row),parent=store.Load().flows[row.parentFlowId];if(parent.status!=='CLAIMED'||parent.sessionExpiresAt<=now())Fail('BOOTSTRAP_FLOW_INVALID');Boot().Verify(row,Canonical(row,'CLAIM'),body.signature);CheckMeasurement(row,artifact,{binarySha512:body.binarySha512,binaryCrc64:body.crc64,codeSha512:body.oCodeSha512,codeCrc64:body.oCodeCrc64});Boot().ReadArtifactBytes(artifact);const license=License(row);
 store.Atomic(next=>{const item=next.overlays[row.id];if(item.status!=='READY')Fail('BOOTSTRAP_LAUNCHER_USED',409);item.status='CLAIMED';item.claimedAt=now();item.claimRecoveryUntil=Math.min(row.expiresAt,item.claimedAt+30000);item.claimFingerprint=fingerprint;item.lastVerifiedAt=now();item.sessionExpiresAt=Math.min(now()+SESSION_MS,store.Load().flows[row.parentFlowId].sessionExpiresAt,license.expiresAt||Number.MAX_SAFE_INTEGER);item.sessionNonce=nonce();item.sessionHash=sha(SessionToken(item));delete item.ticketNonce;item.chunkOffsets=[];});
 const claimed=Rows()[row.id];Audit('CLAIMED',claimed);return ClaimResult(claimed);
}
function ClaimResult(row){return {sessionId:row.sessionId,sessionToken:SessionToken(row),expiresAt:row.sessionExpiresAt,release:Boot().Release(RequireArtifact(row))};}
function Session(id,token){const row=Object.values(Rows()).find(r=>r.sessionId===id);if(!row||!row.sessionHash||!Boot().EqualHash(token,row.sessionHash))Fail('BOOTSTRAP_SESSION_INVALID',401);return row;}
function CheckMeasurement(row,artifact,body){if(!/^[a-f0-9]{128}$/.test(body.binarySha512||'')||!/^[A-F0-9]{16}$/.test(body.binaryCrc64||'')||!/^[a-f0-9]{128}$/.test(body.codeSha512||'')||!/^[A-F0-9]{16}$/.test(body.codeCrc64||''))Fail('BOOTSTRAP_INPUT_INVALID',400);Boot().CheckFile(artifact,body.binarySha512,body.binaryCrc64,{stage:'O',row});if(artifact.codeSha512!==body.codeSha512||artifact.codeCrc64!==body.codeCrc64){Revoke(row.sessionId,{reason:'CODE_DIGEST_MISMATCH'},'INTEGRITY_REPORT');Fail('BOOTSTRAP_CODE_MISMATCH');}}
function AuthenticateIntegrityReport(body){const row=Session(body.sessionId,body.sessionToken),artifact=Live(row);if(row.status!=='CLAIMED'||body.machineId!==undefined&&body.machineId!==row.machineId)Fail('BOOTSTRAP_SESSION_INVALID');return {...row,stage:'O',reportContextId:row.sessionId,integrityArtifact:{id:artifact.id,hashVersion:3,crcLayers:artifact.crcLayers,sha512:artifact.sha512,crc64:artifact.crc64,fileXxh3_128:artifact.xxh3_128,fileBlake3:artifact.blake3,codeSha512:artifact.codeSha512,codeCrc64:artifact.codeCrc64,codeXxh3_128:artifact.codeXxh3_128,codeBlake3:artifact.codeBlake3}};}
function Verify(body){Fields(body,['sessionId','sessionToken','machineId','binarySha512','binaryCrc64','codeSha512','codeCrc64']);const row=Session(body.sessionId,body.sessionToken),artifact=Live(row);if(row.status!=='CLAIMED'||body.machineId!==row.machineId)Fail('BOOTSTRAP_SESSION_INVALID');CheckMeasurement(row,artifact,body);require('./desktopIntegrityReports').RequireSnapshot(row,'O');const authority=require('./desktopSecurityAuthority');authority.RequireFresh(row,'O','verify',authority.Binding(row.sessionId,artifact.sha512));const license=License(row),parent=store.Load().flows[row.parentFlowId],transferConfirmed=Transferred(row,parent),expiresAt=Math.min(now()+SESSION_MS,transferConfirmed?Number.MAX_SAFE_INTEGER:parent.sessionExpiresAt,license.expiresAt||Number.MAX_SAFE_INTEGER);store.Atomic(next=>{const item=next.overlays[row.id];item.sessionExpiresAt=expiresAt;item.lastVerifiedAt=now();item.authorizedAt=item.lastVerifiedAt;delete item.claimRecoveryUntil;delete item.claimFingerprint;});return {status:'ACTIVE',leaseExpiresAt:expiresAt,serverTime:now(),expiresAt,handoffVersion:1,transferConfirmed,parentSessionId:row.parentSessionId};}
function TransferCanonical(parentId,overlayId){return ['GAME-OVERLAY-TRANSFER-V1',parentId,overlayId].join('\n');}
function EqualStrong(value,expected){return typeof value==='string'&&typeof expected==='string'&&/^[a-f0-9]{128}$/.test(expected)&&crypto.timingSafeEqual(Buffer.from(sha512(value),'hex'),Buffer.from(expected,'hex'));}
// A receipt verifier is never a bootstrap session credential. B's ordinary
// session hash/nonces are retired atomically, and only exact commit recovery or
// best-effort close can use this short-lived, non-reconstructible digest.
function AuthenticateRetiredParent(parent,token){if(!parent?.closedByOverlay||parent.status!=='CLOSED'||!Number.isSafeInteger(parent.transferRecoveryUntil)||parent.transferRecoveryUntil<=now()||!EqualStrong(token,parent.transferReceiptHash))Fail('BOOTSTRAP_SESSION_INVALID',401);return parent;}
function CommitResult(row){return {handoffVersion:1,status:'TRANSFERRED',parentSessionId:row.parentSessionId,overlayId:row.id,overlaySessionId:row.sessionId};}
function Commit(body){
 Fields(body,['handoffVersion','sessionId','sessionToken','overlayId','signature']);if(body.handoffVersion!==1||!/^[A-F0-9]{24}$/.test(body.overlayId||'')||!/^[A-F0-9]{24}$/.test(body.sessionId||'')||typeof body.sessionToken!=='string'||body.sessionToken.length>200||typeof body.signature!=='string'||body.signature.length>1000)Fail('BOOTSTRAP_INPUT_INVALID',400);
 const row=Rows()[body.overlayId],parent=row&&store.Load().flows[row.parentFlowId];if(!row||!parent||body.sessionId!==row.parentSessionId)Fail('BOOTSTRAP_SESSION_INVALID',401);
 const fingerprint=sha512(JSON.stringify([1,body.sessionId,body.sessionToken,body.overlayId,body.signature]));
 if(Transferred(row,parent)){AuthenticateRetiredParent(parent,body.sessionToken);if(parent.transferFingerprint!==fingerprint)Fail('BOOTSTRAP_REQUEST_REUSED',409);Boot().Verify(parent,TransferCanonical(parent.sessionId,row.id),body.signature);Live(row);return CommitResult(row);}
 const authenticated=Boot().SessionAuthenticated(body.sessionId,body.sessionToken);if(authenticated.id!==parent.id||parent.status!=='CLAIMED'||parent.sessionExpiresAt<=now())Fail('BOOTSTRAP_SESSION_CLOSED');
 Live(row);if(row.status!=='CLAIMED'||!Number.isSafeInteger(row.authorizedAt)||row.authorizedAt<row.claimedAt||row.authorizedAt+TRANSFER_RECOVERY_MS<=now())Fail('BOOTSTRAP_OVERLAY_NOT_READY',409);
 Boot().Verify(parent,TransferCanonical(parent.sessionId,row.id),body.signature);require('./desktopIntegrityReports').RequireSnapshot(row,'O');
 const license=License(row),at=now();
 store.Atomic(next=>{const item=next.overlays[row.id],flow=next.flows[parent.id];if(item.status!=='CLAIMED'||flow.status!=='CLAIMED'||item.transferVersion!==undefined)Fail('BOOTSTRAP_SESSION_CLOSED');item.transferVersion=1;item.transferredAt=at;item.sessionExpiresAt=Math.min(at+SESSION_MS,license.expiresAt||Number.MAX_SAFE_INTEGER);flow.status='CLOSED';flow.closedAt=at;flow.closedByOverlay=true;flow.overlayTransferVersion=1;flow.transferredOverlayId=item.id;flow.transferredAt=at;flow.transferRecoveryUntil=at+TRANSFER_RECOVERY_MS;flow.transferReceiptHash=sha512(body.sessionToken);flow.transferFingerprint=fingerprint;flow.licenseLeaseExpiresAt=0;Boot().RetireFlow(flow);delete flow.sessionHash;});
 const committed=Rows()[row.id];Audit('TRANSFERRED',committed);try{require('../storage/audit').LogEvent('DESKTOP_BOOTSTRAP_CLOSED',JSON.stringify({sessionId:parent.sessionId,licenseId:parent.licenseId,reason:'OVERLAY_TRANSFERRED',overlayId:row.id}));}catch(_){console.error('OVERLAY_AUDIT_FAILED');}return CommitResult(committed);
}
function Close(body){Fields(body,['sessionId','sessionToken']);const row=Session(body.sessionId,body.sessionToken);if(!TERMINAL.includes(row.status)){store.Atomic(next=>{const item=next.overlays[row.id];item.status='CLOSED';item.closedAt=now();Retire(item);});Audit('CLOSED',row);}return {sessionId:row.sessionId,status:Rows()[row.id].status};}
function Revoke(sessionId,body,actor){const row=Object.values(Rows()).find(r=>r.sessionId===sessionId);if(!row)Fail('BOOTSTRAP_SESSION_INVALID',404);store.Atomic(next=>{const item=next.overlays[row.id];item.status='REVOKED';item.revokedAt=now();item.reason=String(body.reason||'REVOKED').slice(0,300);Retire(item);});Audit('REVOKED',row);return View(Rows()[row.id]);}
function Prune(){const expired=Object.values(Rows()).filter(r=>!TERMINAL.includes(r.status)&&(r.status==='CLAIMED'?r.sessionExpiresAt:r.expiresAt)<=now()),receipts=Object.values(store.Load().flows).filter(r=>r.transferRecoveryUntil!==undefined&&r.transferRecoveryUntil<=now());if(expired.length||receipts.length)store.Atomic(next=>{for(const row of expired){const item=next.overlays[row.id];item.status='EXPIRED';Retire(item);}for(const row of receipts){const item=next.flows[row.id];delete item.transferReceiptHash;delete item.transferFingerprint;delete item.transferRecoveryUntil;}});}
function View(row){return {id:row.sessionId,flowId:row.id,parentSessionId:row.parentSessionId,component:'O',status:row.status,online:row.status==='CLAIMED'&&row.sessionExpiresAt>now(),deviceId:row.deviceId,machineId:row.machineId,releaseId:row.releaseId,licenseId:row.licenseId,createdAt:row.createdAt,claimedAt:row.claimedAt||0,expiresAt:row.sessionExpiresAt||row.expiresAt,lastVerifiedAt:row.lastVerifiedAt,reason:row.reason||''};}
function List(){Prune();return Object.values(Rows()).map(View);}
function Audit(kind,row){try{require('../storage/audit').LogEvent('DESKTOP_OVERLAY_'+kind,JSON.stringify({overlayId:row.id,sessionId:row.sessionId,parentSessionId:row.parentSessionId,licenseId:row.licenseId,releaseId:row.releaseId}));}catch(_){console.error('OVERLAY_AUDIT_FAILED');}}
function ValidateStore(db){if(!plain(db.overlays))throw Error('OVERLAY_STORE_INVALID');const sessions=new Set(Object.values(db.flows).map(r=>r.sessionId));for(const [key,row]of Object.entries(db.overlays)){if(!plain(row)||key!==row.id||!/^[A-F0-9]{24}$/.test(key)||!/^[A-F0-9]{24}$/.test(row.sessionId)||sessions.has(row.sessionId)||!['PREPARED','READY','CLAIMED',...TERMINAL].includes(row.status)||db.artifacts[row.releaseId]?.component!=='O'||db.flows[row.parentFlowId]?.sessionId!==row.parentSessionId||db.flows[row.parentFlowId]?.overlayReleaseId!==row.releaseId||row.deviceId!==db.flows[row.parentFlowId]?.deviceId||row.publicKey!==db.flows[row.parentFlowId]?.publicKey||row.machineId!==db.flows[row.parentFlowId]?.machineId||row.machinePolicyGeneration!==db.flows[row.parentFlowId]?.machinePolicyGeneration||row.licenseId!==db.flows[row.parentFlowId]?.licenseId||!Number.isSafeInteger(row.createdAt)||!Number.isSafeInteger(row.expiresAt)||row.expiresAt<=row.createdAt||!/^[a-f0-9]{128}$/.test(row.ticketBinding)||!/^[a-f0-9]{64}$/.test(row.ticketHash)||!/^[a-f0-9]{64}$/.test(row.fingerprint)||typeof row.requestId!=='string')throw Error('OVERLAY_STORE_INVALID');sessions.add(row.sessionId);if((row.claimRecoveryUntil===undefined)!==(row.claimFingerprint===undefined)||row.claimRecoveryUntil!==undefined&&(row.status!=='CLAIMED'||!Number.isSafeInteger(row.claimRecoveryUntil)||row.claimRecoveryUntil<row.claimedAt||row.claimRecoveryUntil>Math.min(row.expiresAt,row.claimedAt+30000)||!/^([a-f0-9]{64})$/.test(row.claimFingerprint)))throw Error('OVERLAY_STORE_INVALID');if(!Array.isArray(row.chunkOffsets)||row.chunkOffsets.length>256||new Set(row.chunkOffsets).size!==row.chunkOffsets.length||row.chunkOffsets.some(o=>!Number.isSafeInteger(o)||o<0||o>=db.artifacts[row.releaseId].size||o%CHUNK_SIZE))throw Error('OVERLAY_STORE_INVALID');if(['PREPARED','READY'].includes(row.status)){if(!/^[a-f0-9]{48}$/.test(row.ticketNonce)||row.ticketHash!==TokenHash(db.secret,'OVERLAY-HANDOFF',row.id,row.ticketNonce)||row.ticketBinding!==TokenBinding(db.secret,'OVERLAY-HANDOFF',row.id,row.ticketNonce))throw Error('OVERLAY_STORE_INVALID');}else if(row.ticketNonce!==undefined)throw Error('OVERLAY_STORE_INVALID');if(row.status==='CLAIMED'){if(!/^[a-f0-9]{48}$/.test(row.sessionNonce)||row.sessionHash!==TokenHash(db.secret,'OVERLAY-SESSION',row.sessionId,row.sessionNonce)||!Number.isSafeInteger(row.sessionExpiresAt)||!Number.isSafeInteger(row.claimedAt))throw Error('OVERLAY_STORE_INVALID');}else if(row.sessionNonce!==undefined)throw Error('OVERLAY_STORE_INVALID');if(TERMINAL.includes(row.status)&&!Number.isSafeInteger(row.retiredAt))throw Error('OVERLAY_STORE_INVALID');}return db.overlays;}
function TokenBinding(secret,domain,key,value){return sha512(crypto.createHmac('sha256',Buffer.from(secret,'hex')).update(['GAME-OVERLAY-V1',domain,key,value].join('|')).digest('base64url'));}
function TokenHash(secret,domain,key,value){return sha(crypto.createHmac('sha256',Buffer.from(secret,'hex')).update(['GAME-OVERLAY-V1',domain,key,value].join('|')).digest('base64url'));}
function ValidateParentTransfer(db,parent){
 const fields=['closedByOverlay','overlayTransferVersion','transferredOverlayId','transferredAt'],receipt=['transferRecoveryUntil','transferReceiptHash','transferFingerprint'];
 if(fields.every(k=>parent[k]===undefined)){if(receipt.some(k=>parent[k]!==undefined))throw Error('OVERLAY_STORE_INVALID');return;}
 const row=db.overlays?.[parent.transferredOverlayId];
 if(parent.closedByOverlay!==true||parent.overlayTransferVersion!==1||!['CLOSED','REVOKED','EXPIRED'].includes(parent.status)||!Number.isSafeInteger(parent.transferredAt)||parent.transferredAt!==parent.closedAt||parent.retiredAt===undefined||parent.sessionHash!==undefined||parent.sessionNonce!==undefined||!row||row.parentFlowId!==parent.id||row.transferVersion!==1||row.transferredAt!==parent.transferredAt)throw Error('OVERLAY_STORE_INVALID');
 if(receipt.some(k=>parent[k]!==undefined)&&(!Number.isSafeInteger(parent.transferRecoveryUntil)||parent.transferRecoveryUntil!==parent.transferredAt+TRANSFER_RECOVERY_MS||!/^[a-f0-9]{128}$/.test(parent.transferReceiptHash)||!/^[a-f0-9]{128}$/.test(parent.transferFingerprint)))throw Error('OVERLAY_STORE_INVALID');
}
function ValidateTransferRows(db){for(const row of Object.values(db.overlays||{})){if(row.authorizedAt!==undefined&&(!Number.isSafeInteger(row.authorizedAt)||row.authorizedAt<row.claimedAt||row.authorizedAt!==row.lastVerifiedAt))throw Error('OVERLAY_STORE_INVALID');if(row.transferVersion===undefined){if(row.transferredAt!==undefined)throw Error('OVERLAY_STORE_INVALID');continue;}const parent=db.flows[row.parentFlowId];if(row.transferVersion!==1||!Number.isSafeInteger(row.transferredAt)||row.transferredAt<row.claimedAt||row.authorizedAt===undefined||parent?.transferredOverlayId!==row.id||parent?.transferredAt!==row.transferredAt||parent?.overlayTransferVersion!==1||parent?.closedByOverlay!==true||!['CLOSED','REVOKED','EXPIRED'].includes(parent.status))throw Error('OVERLAY_STORE_INVALID');}}
function Execute(body){Prune();switch(body.action){case 'overlayChunk':return Chunk(body);case 'overlayFinish':return Finish(body);case 'overlayClaim':return Claim(body);case 'overlayVerify':return Verify(body);case 'overlayCommit':return Commit(body);case 'overlayClose':return Close(body);default:Fail('BOOTSTRAP_INPUT_INVALID',400);}}
module.exports={Prepare,Execute,AuthenticateIntegrityReport,AuthenticateRetiredParent,Revoke,Prune,List,ValidateStore,ValidateParentTransfer,ValidateTransferRows};
