'use strict';

const crypto=require('crypto');
const state=require('../core/state');
const {Now,SafeField}=require('../core/utils');
const challenges=new Map();
const B64=b=>Buffer.from(b).toString('base64url');
const Buf=s=>Buffer.from(String(s||''),'base64url');

function Context(req){
    const host=String(req.headers.host||'').split(':')[0].toLowerCase();
    const rpId=String(process.env.WEBAUTHN_RP_ID||host).trim().toLowerCase();
    const proto=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https'||(req.socket&&req.socket.encrypted)?'https':'http';
    const origin=String(process.env.WEBAUTHN_ORIGIN||`${proto}://${req.headers.host||host}`).replace(/\/$/,'');
    return{rpId,origin};
}
function NewChallenge(kind,role,sessionId,req){const ctx=Context(req),id=`PKC-${crypto.randomBytes(10).toString('hex').toUpperCase()}`,challenge=B64(crypto.randomBytes(32));const item={id,kind,role,sessionId:sessionId||'',challenge,...ctx,createdAt:Now(),expiresAt:Now()+5*60000};challenges.set(id,item);return item;}
function CheckClientData(item,value,type){let data;try{data=JSON.parse(Buf(value).toString('utf8'));}catch(_){throw new Error('PASSKEY_CLIENT_DATA_INVALID');}if(data.type!==type||data.challenge!==item.challenge||data.origin!==item.origin)throw new Error('PASSKEY_CHALLENGE_INVALID');return data;}
function CheckAuthData(item,value,requireUv=true){const b=Buf(value);if(b.length<37)throw new Error('PASSKEY_AUTH_DATA_INVALID');const rpHash=crypto.createHash('sha256').update(item.rpId).digest();if(!crypto.timingSafeEqual(b.subarray(0,32),rpHash))throw new Error('PASSKEY_RP_INVALID');const flags=b[32];if(!(flags&1)||(requireUv&&!(flags&4)))throw new Error('PASSKEY_USER_VERIFICATION_REQUIRED');return{buffer:b,flags,signCount:b.readUInt32BE(33)};}
function CredentialsForRole(role){return Array.from(state.production.passkeyCredentials.values()).filter(x=>x.role===role&&!x.revokedAt);}
function RegistrationBegin(session,req){if(!session||session.role!=='admin')return{ok:false,reason:'ADMIN_REQUIRED'};const item=NewChallenge('CREATE','admin',session.id,req);return{ok:true,challengeId:item.id,publicKey:{challenge:item.challenge,rp:{name:'Relay Operations',id:item.rpId},user:{id:B64(Buffer.from(`admin:${session.id}`)),name:'relay-admin',displayName:'Relay Administrator'},pubKeyCredParams:[{type:'public-key',alg:-7}],timeout:300000,attestation:'none',authenticatorSelection:{residentKey:'preferred',userVerification:'required'}}};}
function RegistrationFinish(session,req,body){const item=challenges.get(String(body.challengeId||''));if(!item||item.kind!=='CREATE'||item.expiresAt<=Now()||!session||item.sessionId!==session.id)return{ok:false,reason:'PASSKEY_CHALLENGE_INVALID'};try{CheckClientData(item,body.clientDataJSON,'webauthn.create');CheckAuthData(item,body.authenticatorData,true);const publicKey=Buf(body.publicKeySpki);const parsed=crypto.createPublicKey({key:publicKey,type:'spki',format:'der'});if(parsed.asymmetricKeyType!=='ec')throw new Error('PASSKEY_KEY_TYPE_INVALID');const credentialId=String(body.credentialId||'');if(!credentialId||Buf(credentialId).length<16)throw new Error('PASSKEY_CREDENTIAL_INVALID');const id=crypto.createHash('sha256').update(Buf(credentialId)).digest('hex').slice(0,24).toUpperCase();const record={id,role:'admin',credentialId,publicKeySpki:B64(publicKey),rpId:item.rpId,name:SafeField(body.name||`Admin key ${id.slice(-6)}`).slice(0,64),createdAt:Now(),lastUsedAt:0,signCount:0,revokedAt:0};state.production.passkeyCredentials.set(id,record);challenges.delete(item.id);require('../storage/database').SaveDatabase();require('../storage/audit').LogEvent('PASSKEY_REGISTERED',`${id} / admin`);return{ok:true,credential:{...record,publicKeySpki:undefined}};}catch(error){return{ok:false,reason:error.message||'PASSKEY_REGISTRATION_FAILED'};}}
function LoginBegin(role,req){role=String(role||'').toLowerCase();const creds=CredentialsForRole(role);if(!creds.length)return{ok:false,reason:'PASSKEY_NOT_REGISTERED'};const item=NewChallenge('GET',role,'',req);return{ok:true,challengeId:item.id,publicKey:{challenge:item.challenge,rpId:item.rpId,allowCredentials:creds.map(x=>({type:'public-key',id:x.credentialId})),timeout:300000,userVerification:'required'}};}
function LoginFinish(req,body){const item=challenges.get(String(body.challengeId||''));if(!item||item.kind!=='GET'||item.expiresAt<=Now())return{ok:false,reason:'PASSKEY_CHALLENGE_INVALID'};const cred=CredentialsForRole(item.role).find(x=>x.credentialId===String(body.credentialId||''));if(!cred)return{ok:false,reason:'PASSKEY_CREDENTIAL_NOT_FOUND'};try{CheckClientData(item,body.clientDataJSON,'webauthn.get');const auth=CheckAuthData(item,body.authenticatorData,true);const signed=Buffer.concat([auth.buffer,crypto.createHash('sha256').update(Buf(body.clientDataJSON)).digest()]);const key=crypto.createPublicKey({key:Buf(cred.publicKeySpki),type:'spki',format:'der'});if(!crypto.verify('sha256',signed,key,Buf(body.signature)))throw new Error('PASSKEY_SIGNATURE_INVALID');if(cred.signCount&&auth.signCount&&auth.signCount<=cred.signCount)throw new Error('PASSKEY_COUNTER_REPLAY');cred.signCount=auth.signCount;cred.lastUsedAt=Now();challenges.delete(item.id);require('../storage/database').SaveDatabase();require('../storage/audit').LogEvent('PASSKEY_AUTH',`${cred.id} / ${item.role}`);return{ok:true,role:item.role,credentialId:cred.id};}catch(error){return{ok:false,reason:error.message||'PASSKEY_AUTH_FAILED'};}}
function List(){return Array.from(state.production.passkeyCredentials.values()).map(x=>({id:x.id,role:x.role,name:x.name,createdAt:x.createdAt,lastUsedAt:x.lastUsedAt,signCount:x.signCount,revokedAt:x.revokedAt||0}));}
function Revoke(id,actor){const item=state.production.passkeyCredentials.get(String(id||'').toUpperCase());if(!item)return{ok:false,reason:'PASSKEY_NOT_FOUND'};item.revokedAt=Now();item.revokedBy=SafeField(actor).slice(0,64);require('../storage/database').SaveDatabase();return{ok:true};}
function Cleanup(){const now=Now();for(const [k,v]of challenges)if(v.expiresAt<=now)challenges.delete(k);}
module.exports={RegistrationBegin,RegistrationFinish,LoginBegin,LoginFinish,List,Revoke,Cleanup};
