'use strict';
const {JSDOM,VirtualConsole}=require('jsdom');
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const root=path.resolve(__dirname,'..');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'relay-dom-test-'));
process.env.DATA_DIR=temp;process.env.STORAGE_ENGINE='json';
const state=require(root+'/core/state');require(root+'/core/utils').EnsureDirs();
const api=require(root+'/web/webApi'),support=require(root+'/services/supportCenter');
const id='A123456789ABCDEF',c={type:'client',clientId:id,connected:true,deviceAuthVerified:true,permissionsGranted:true};
c.socket={destroyed:false,remoteAddress:'127.0.0.1',write(){return true}};c.socket.__relayConnection=c;
state.clients.set(id,c);state.clientIdentities.set('DOM-TEST',{id,serverId:''});
support.Handle(c,'SUPPORT_OPEN|'+id);
support.Handle(c,'SUPPORT_SEND_V2|DOM_MESSAGE_1|1|'+Buffer.from('첫 문의 <script>unsafe</script>').toString('base64'));
support.Handle(c,'SUPPORT_BOT_OPEN|'+id);
const virtualConsole=new VirtualConsole();const errors=[];virtualConsole.on('jsdomError',e=>errors.push(e.message));
const html=fs.readFileSync(root+'/public/index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,'');
const dom=new JSDOM(html,{url:'https://fixture.invalid/',runScripts:'outside-only',virtualConsole});
const style=dom.window.document.createElement('style');style.textContent=['admin.css','admin-theme.css','admin-navigation.css'].map(n=>fs.readFileSync(root+'/public/'+n,'utf8')).join('\n');dom.window.document.head.appendChild(style);
const w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.matchMedia=()=>({matches:false,addListener(){}});
w.EventSource=class {addEventListener(){}close(){}};
w.fetch=async(url,options={})=>{
 if(url==='/api/session')return {status:200,ok:true,text:async()=>JSON.stringify({ok:true,role:'admin',csrf:'TEST',expiresAt:Date.now()+999999})};
 let status=0,body='';
 const req=require('node:stream').Readable.from(options.body?[Buffer.from(options.body)]:[]); Object.assign(req,{method:options.method||'GET',url,headers:{},socket:{remoteAddress:'127.0.0.1'}});
 const res={writeHead(s){status=s},end(s){body=s}};
 if(req.method!=='GET') assert.match(url,/\/read$|^\/api\/support\/knowledge(?:\/delete)?$/,'Only generated fixture read/FAQ state may change');
 await api.HandleApiRequest(req,res,{role:'admin',id:'TEST',ip:'127.0.0.1'});
 return {status,ok:status>=200&&status<300,text:async()=>body};
};
for(const name of [...fs.readFileSync(root+'/public/index.html','utf8').matchAll(/<script src="\/(admin[^?"]+)\?/g)].map(m=>m[1].slice(0,-3))) new (require('vm').Script)(fs.readFileSync(root+'/public/'+name+'.js','utf8')).runInContext(dom.getInternalVMContext());
const settle=()=>new Promise(resolve=>setTimeout(resolve,30));
(async()=>{try{
 await settle();
 assert.ok(style.sheet.cssRules.length>200);
 assert.equal(w.getComputedStyle(w.document.querySelector('.login-card .primary')).backgroundColor,'rgb(32, 35, 42)');
 assert.equal(w.getComputedStyle(w.document.querySelector('.login-card .primary')).color,'rgb(255, 255, 255)');
 assert.match(w.readableApiError('PERMISSIONS_REQUIRED'),/필수 권한/);
 assert.equal(w.document.querySelector('#app').classList.contains('hidden'),false);
 assert.equal(w.document.querySelector('#page-title').textContent,'대시보드');
 assert.equal(w.document.querySelectorAll('.cards .card').length,11);
 const menu=w.document.querySelector('#menu-toggle');menu.click();
 assert.equal(menu.getAttribute('aria-expanded'),'true');
 w.document.querySelector('[data-view="support"]').click();await settle();
 assert.equal(menu.getAttribute('aria-expanded'),'false');
 assert.equal(w.document.querySelector('#page-title').textContent,'고객센터');
 assert.equal(w.document.querySelector('[data-support-availability="OFFLINE"]').getAttribute('aria-pressed'),'true');
 assert.equal(w.document.querySelectorAll('.support-thread').length,1);
 w.document.querySelector('.support-thread').click();await settle();
 assert.equal(w.document.querySelectorAll('.support-message script').length,0);
 assert.match(w.document.querySelector('.support-transcript').textContent,/<script>unsafe<\/script>/);
 const draft=w.document.querySelector('#support-draft');draft.value='전송하지 않은 답변';draft.dispatchEvent(new w.Event('input',{bubbles:true}));
 await w.renderSupportCenter();assert.equal(w.document.querySelector('#support-draft'),draft);assert.equal(draft.value,'전송하지 않은 답변');
 w.document.querySelector('[data-view="reinstallblocks"]').click();await settle();
 assert.equal(w.document.querySelector('#page-title').textContent,'재설치 차단');
 w.document.querySelector('[data-view="support"]').click();await settle();
 assert.equal(w.document.querySelector('#support-draft').value,'전송하지 않은 답변');
 menu.click();w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(menu.getAttribute('aria-expanded'),'false');
 // FAQ editor persists changes through the real API without replacing the conversation draft.
 assert.ok(w.document.querySelector('.from-bot'));assert.match(w.document.querySelector('.from-bot').textContent,/FAQ 안내 봇/);
 const select=w.document.querySelector('#support-faq-select');assert.ok(select.options.length>=7);select.value='FAQ_CHARGE';select.dispatchEvent(new w.Event('change',{bubbles:true}));
 let form=w.document.querySelector('#support-faq-form');form.elements.answer.value='웹에서 수정한 안전한 안내 <script>실행 금지</script>';
 form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await settle();
 assert.equal(require('../services/supportKnowledge').Admin().items.find(x=>x.id==='FAQ_CHARGE').answer,'웹에서 수정한 안전한 안내 <script>실행 금지</script>');
 assert.match(w.document.querySelector('#support-faq-status').textContent,/반영/);assert.equal(w.document.querySelector('#support-draft').value,'전송하지 않은 답변');
 assert.equal(w.document.querySelectorAll('#support-knowledge-editor script').length,0);
 // An unsaved FAQ edit remains intact across the automatic support refresh.
 form=w.document.querySelector('#support-faq-form');form.elements.question.value='작성 중인 질문';form.elements.question.focus();await w.renderSupportCenter();
 assert.equal(w.document.querySelector('#support-faq-form'),form);assert.equal(form.elements.question.value,'작성 중인 질문');
 assert.match(w.readableApiError('INVALID_SUPPORT_FAQ'),/검색어/);
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('DOM REGRESSION PASS: dashboard, localized navigation, mobile menu state, support selection, escaped content, draft preservation, permission error labels, bot bubbles, safe FAQ editing and preserved drafts');
}finally{w.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
